server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
  show-login-endpoint: true

spring:
  profiles:
    active: default

  datasource:
    # для запуска в docker поменят на 5430
    # для локального на 5432
    url: jdbc:postgresql://localhost:5430/crm
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: crm
        format_sql: true
  flyway:
    enable: true
    locations:
      - db.migration
    default-schema: crm

logging:
  level:
    shift.lab.crm: debug
  file.name: logs/app.log
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg%n"
    file: "%d [%t] %-5level %logger{36} - %msg%n"

